### ISSUE TITLE
why does set_user/get_user have an id_type argument

### ISSUE THREAD

**Issue by roccojonack** [Arteris-IP/tlm2-interfaces#3]
We had discussed this topic for the ID and took the id_type out. I don't see the need for the user field either. I think the id_type in the common struct can be removed, because the transaction itself is clearly identified by its properties whether you use ARUSER or AWUSER.

**Comment by eyck** [comment]
Actually the user property describes not only ARUSER/AWUSER rather alos RUSER/BUSER as well as and WUSER. Since they might carry different information they cannot be mixed into one property.
